language: scala
scala:
   - 2.10.4
jdk:
   - oraclejdk7

#script: "sbt clean scoverage:test"
script: "sbt test"

#after_script:
#   - sbt 'test:runMain ml.wolfe.benchmark.AllBenchmarks '$TRAVIS_BUILD_NUMBER' travis '$TRAVIS_BRANCH

notifications:
  email: false
